import { AIGenerateRequest, AIGenerateResponse } from '@/types';

// Use gemini-1.5-flash as a more stable model
const GEMINI_API_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent';

export async function generateHuntWithAI(
  request: AIGenerateRequest,
  apiKey: string
): Promise<AIGenerateResponse> {
  const prompt = `You are a creative scavenger hunt designer. Generate a fun, engaging scavenger hunt based on these parameters:

Theme: ${request.theme}
Location: ${request.location || 'Any location (indoor/outdoor flexible)'}
Difficulty: ${request.difficulty}
Number of challenges: ${request.challengeCount}
Estimated duration: ${request.duration} minutes

Generate a JSON response with this exact structure:
{
  "hunt": {
    "title": "Creative hunt title",
    "description": "Engaging 2-3 sentence description",
    "difficulty": "${request.difficulty}",
    "estimatedTime": ${request.duration},
    "challengeCount": ${request.challengeCount},
    "isPublic": true,
    "tags": ["tag1", "tag2", "tag3"],
    "location": "${request.location || 'Flexible'}"
  },
  "challenges": [
    {
      "title": "Challenge title",
      "description": "Clear description of what to find/do",
      "points": 10-50 based on difficulty,
      "type": "photo" | "gps" | "text",
      "hint": "Optional helpful hint",
      "order": 1
    }
  ]
}

Make the challenges creative, fun, and achievable. Use varied challenge types.
Points should be 10-20 for easy, 20-35 for medium, 35-50 for hard challenges.
Respond ONLY with valid JSON, no markdown or explanations.`;

  let response: Response;
  try {
    response = await fetch(`${GEMINI_API_URL}?key=${apiKey}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{ text: prompt }]
        }],
        generationConfig: {
          temperature: 0.8,
          topK: 40,
          topP: 0.95,
          maxOutputTokens: 2048,
        }
      }),
    });
  } catch (fetchError) {
    console.error('Gemini API fetch error:', fetchError);
    throw new Error(`Failed to connect to Gemini API: ${fetchError instanceof Error ? fetchError.message : 'Network error'}`);
  }

  if (!response.ok) {
    // Try to get error details from response
    let errorDetails = response.statusText;
    try {
      const errorText = await response.text();
      // Check if it's JSON error response
      if (errorText.startsWith('{')) {
        const errorJson = JSON.parse(errorText);
        errorDetails = errorJson.error?.message || errorText;
      }
    } catch {
      // Ignore parse errors, use statusText
    }
    console.error(`Gemini API error: ${response.status} - ${errorDetails}`);
    throw new Error(`AI generation failed: ${response.status} ${errorDetails}`);
  }

  let data;
  try {
    data = await response.json();
  } catch (jsonError) {
    console.error('Failed to parse Gemini response as JSON:', jsonError);
    throw new Error('Invalid response from Gemini API');
  }

  const textContent = data.candidates?.[0]?.content?.parts?.[0]?.text;

  if (!textContent) {
    console.error('No content in Gemini response:', JSON.stringify(data).slice(0, 500));
    throw new Error('No content generated by AI');
  }

  // Parse JSON from response (handle potential markdown wrapping)
  const jsonMatch = textContent.match(/\{[\s\S]*\}/);
  if (!jsonMatch) {
    console.error('No JSON found in AI response:', textContent.slice(0, 500));
    throw new Error('Invalid JSON response from AI');
  }

  try {
    return JSON.parse(jsonMatch[0]) as AIGenerateResponse;
  } catch (parseError) {
    console.error('Failed to parse AI JSON:', jsonMatch[0].slice(0, 500));
    throw new Error(
      `Failed to parse AI response as JSON: ${parseError instanceof Error ? parseError.message : 'Unknown error'}`
    );
  }
}

// Demo hunts for showcase
export const demoHunts = [
  {
    id: 'demo-1',
    title: 'Downtown Discovery',
    description: 'Explore the heart of the city and uncover hidden gems, historic landmarks, and local favorites.',
    difficulty: 'easy' as const,
    estimatedTime: 45,
    challengeCount: 8,
    participantCount: 234,
    location: 'City Center',
    isPublic: true,
    createdAt: new Date().toISOString(),
    createdBy: 'Scavengers Team',
    tags: ['urban', 'walking', 'landmarks'],
  },
  {
    id: 'demo-2',
    title: 'Nature Navigator',
    description: 'Venture into the wilderness and discover the beauty of nature through this outdoor adventure.',
    difficulty: 'medium' as const,
    estimatedTime: 90,
    challengeCount: 12,
    participantCount: 156,
    location: 'Local Park',
    isPublic: true,
    createdAt: new Date().toISOString(),
    createdBy: 'Scavengers Team',
    tags: ['nature', 'outdoor', 'hiking'],
  },
  {
    id: 'demo-3',
    title: 'Museum Mystery',
    description: 'Solve clues and puzzles while exploring art, history, and science in this indoor adventure.',
    difficulty: 'hard' as const,
    estimatedTime: 120,
    challengeCount: 15,
    participantCount: 89,
    location: 'Local Museum',
    isPublic: true,
    createdAt: new Date().toISOString(),
    createdBy: 'Scavengers Team',
    tags: ['museum', 'puzzles', 'educational'],
  },
];
